### ISSUE TITLE
🚀 功能建议：关于新增镜像源public.ecr.aws的申请

### ISSUE THREAD

**Issue by wnark** [dqzboy/Docker-Proxy#56]
### ⚠️ 搜索是否存在类似issue

- [x] 我已经搜索过issues、disscussions和问题总结，没有跟我遇到的问题相关的issue

### 总结

部署kubeflow时，用到了这个镜像:public.ecr.aws/docker/library/python：

https://github.com/kubeflow/manifests/blob/f42cf51011839023c0f3311a52329a3d8ec9ea38/apps/pipeline/upstream/base/installs/multi-user/pipelines-profile-controller/deployment.yaml#L24

请问是否可以官方增加支持该镜像源，或者是否可以配置自定义加速的镜像源，以供访问该镜像

**Comment by wnark** [comment]
> 不会新增其他的上游Registry，你可以修改配置文件，自己定义上游Registry就行 [config](https://github.com/dqzboy/Docker-Proxy/tree/main/config)

好的，谢谢，我试试

**Comment by wnark** [comment]
@dqzboy 请教一下
原始的拉取命令:
docker pull public.ecr.aws/docker/library/python:3.12
我配置了config文件:registry-aws.yml

```
version: 0.1
log:
  fields:
    service: registry
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory   
    blobdescriptorsize: 10000
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

proxy:
  remoteurl: https://public.ecr.aws
  username: 
  password:
  ttl: 168h
```

还配置了docker-compose.yaml
```
  ## public.ecr.aws
  aws:
    container_name: reg-aws
    image: dqzboy/registry:latest
    restart: always
    environment:
      - OTEL_TRACES_EXPORTER=none
      - http_proxy=http://local.http-proxy.srv:10101
      - https_proxy=http://local.http-proxy.srv:10101
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry-aws.yml:/etc/distribution/config.yml
      #- ./htpasswd:/auth/htpasswd
    ports:
      - 60000:5000
    networks:
      - registry-net
```
以及nginx配置
```
server {
    listen       80;
    #listen       443 ssl;
    server_name  aws.docker.srv;
    #ssl_certificate /path/to/your_domain_name.crt;
    #ssl_certificate_key /path/to/your_domain_name.key;
    #ssl_session_timeout 1d;
    #ssl_session_cache   shared:SSL:50m;
    #ssl_session_tickets off;
    #ssl_protocols TLSv1.2 TLSv1.3;
    #ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    #ssl_prefer_server_ciphers on;
    #ssl_buffer_size 8k;
    proxy_connect_timeout 600;
    proxy_send_timeout    600;
    proxy_read_timeout    600;
    send_timeout          600;
    location / {
        proxy_pass   http://localhost:60000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Nginx-Proxy true;
        proxy_buffering off;
        proxy_redirect off;
    }
}

```

现在配好docker配置文件后，拉取镜像命令无法拉取镜像`docker pull aws.docker.srv/docker/library/python:3.12`

容器内的日志`docker logs  reg-aws`为:
```
time="2025-06-03T07:40:11.501489686Z" level=error msg="response completed with error" err.code=unknown err.detail="unauthorized: " err.message="unknown error" go.version=go1.23.7 http.request.host=aws.docker.srv http.request.id=e6e4ccd9-6688-43ce-834e-d283e31bf4d4 http.request.method=GET http.request.remoteaddr=10.0.64.248 http.request.uri="/v2/docker/library/python/blobs/sha256:37927ed901b1b2608b72796c6881bf645480268eca4ac9a37b9219e050bb4d84" http.request.useragent="docker/28.1.1 go/go1.23.8 git-commit/01f442b kernel/5.15.0-139-generic os/linux arch/amd64 UpstreamClient(Docker-Client/28.1.1 \\(linux\\))" http.response.contenttype=application/json http.response.duration=375.422329ms http.response.status=500 http.response.written=84 instance.id=1cc4b10a-4413-484a-90e9-2dd7e8258248 service=registry vars.digest="sha256:37927ed901b1b2608b72796c6881bf645480268eca4ac9a37b9219e050bb4d84" vars.name=docker/library/python version=3.0.0
172.18.0.1 - - [03/Jun/2025:07:40:11 +0000] "GET /v2/docker/library/python/blobs/sha256:37927ed901b1b2608b72796c6881bf645480268eca4ac9a37b9219e050bb4d84 HTTP/1.0" 500 84 "" "docker/28.1.1 go/go1.23.8 git-commit/01f442b kernel/5.15.0-139-generic os/linux arch/amd64 UpstreamClient(Docker-Client/28.1.1 \\(linux\\))"
172.18.0.1 - - [03/Jun/2025:07:40:11 +0000] "GET /v2/docker/library/python/blobs/sha256:1b0cfae6e4d89d02be73031f3512c3504525ee74bbb7677b1cded24e7bd5b5b9 HTTP/1.0" 500 84 "" "docker/28.1.1 go/go1.23.8 git-commit/01f442b kernel/5.15.0-139-generic os/linux arch/amd64 UpstreamClient(Docker-Client/28.1.1 \\(linux\\))"
time="2025-06-03T07:40:11.750043859Z" level=error msg="response completed with error" err.code=unknown err.detail="unauthorized: " err.message="unknown error" go.version=go1.23.7 http.request.host=aws.docker.srv http.request.id=c7960bc3-bfaf-49c4-9db8-ef37a72b8c67 http.request.method=GET http.request.remoteaddr=10.0.64.248 http.request.uri="/v2/docker/library/python/blobs/sha256:1b0cfae6e4d89d02be73031f3512c3504525ee74bbb7677b1cded24e7bd5b5b9" http.request.useragent="docker/28.1.1 go/go1.23.8 git-commit/01f442b kernel/5.15.0-139-generic os/linux arch/amd64 UpstreamClient(Docker-Client/28.1.1 \\(linux\\))" http.response.contenttype=application/json http.response.duration=372.776839ms http.response.status=500 http.response.written=84 instance.id=1cc4b10a-4413-484a-90e9-2dd7e8258248 service=registry vars.digest="sha256:1b0cfae6e4d89d02be73031f3512c3504525ee74bbb7677b1cded24e7bd5b5b9" vars.name=docker/library/python version=3.0.0
time="2025-06-03T07:40:12.627293375Z" level=error msg="response completed with error" err.code=unknown err.detail="unauthorized: " err.message="unknown error" go.version=go1.23.7 http.request.host=aws.docker.srv http.request.id=3670dc6f-8495-46da-84bc-25c22a35e546 http.request.method=GET http.request.remoteaddr=10.0.64.248 http.request.uri="/v2/docker/library/python/blobs/sha256:1b0cfae6e4d89d02be73031f3512c3504525ee74bbb7677b1cded24e7bd5b5b9" http.request.useragent="docker/28.1.1 go/go1.23.8 git-commit/01f442b kernel/5.15.0-139-generic os/linux arch/amd64 UpstreamClient(Docker-Client/28.1.1 \\(linux\\))" http.response.contenttype=application/json http.response.duration=373.488771ms http.response.status=500 http.response.written=84 instance.id=1cc4b10a-4413-484a-90e9-2dd7e8258248 service=registry vars.digest="sha256:1b0cfae6e4d89d02be73031f3512c3504525ee74bbb7677b1cded24e7bd5b5b9" vars.name=docker/library/python version=3.0.0
172.18.0.1 - - [03/Jun/2025:07:40:12 +0000] "GET /v2/docker/library/python/blobs/sha256:1b0cfae6e4d89d02be73031f3512c3504525ee74bbb7677b1cded24e7bd5b5b9 HTTP/1.0" 500 84 "" "docker/28.1.1 go/go1.23.8 git-commit/01f442b kernel/5.15.0-139-generic os/linux arch/amd64 UpstreamClient(Docker-Client/28.1.1 \\(linux\\))"
time="2025-06-03T07:40:14.00422027Z" level=error msg="response completed with error" err.code=unknown err.detail="unauthorized: " err.message="unknown error" go.version=go1.23.7 http.request.host=aws.docker.srv http.request.id=41480989-980c-4d35-aaf9-659c09f78288 http.request.method=GET http.request.remoteaddr=10.0.64.248 http.request.uri="/v2/docker/library/python/blobs/sha256:1b0cfae6e4d89d02be73031f3512c3504525ee74bbb7677b1cded24e7bd5b5b9" http.request.useragent="docker/28.1.1 go/go1.23.8 git-commit/01f442b kernel/5.15.0-139-generic os/linux arch/amd64 UpstreamClient(Docker-Client/28.1.1 \\(linux\\))" http.response.contenttype=application/json http.response.duration=374.94373ms http.response.status=500 http.response.written=84 instance.id=1cc4b10a-4413-484a-90e9-2dd7e8258248 service=registry vars.digest="sha256:1b0cfae6e4d89d02be73031f3512c3504525ee74bbb7677b1cded24e7bd5b5b9" vars.name=docker/library/python version=3.0.0
172.18.0.1 - - [03/Jun/2025:07:40:13 +0000] "GET /v2/docker/library/python/blobs/sha256:1b0cfae6e4d89d02be73031f3512c3504525ee74bbb7677b1cded24e7bd5b5b9 HTTP/1.0" 500 84 "" "docker/28.1.1 go/go1.23.8 git-commit/01f442b kernel/5.15.0-139-generic os/linux arch/amd64 UpstreamClient(Docker-Client/28.1.1 \\(linux\\))"
```

请问哪一步需要优化下呀
